#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SUPABASE_BIN="${SUPABASE_BIN:-$ROOT_DIR/node_modules/.bin/supabase}"
LOCAL_ENV_FILE="$ROOT_DIR/.env.local"
LOCAL_APP_URL="http://localhost:${SQEMES_PORT:-3000}"

usage() {
  cat <<'USAGE'
Usage: npm run local:<command>

Commands:
  local:up          Start local Supabase and the Docker dev app.
  local:fresh       Start local Supabase, reset the local DB, then start the app.
  local:up:preview  Start local Supabase and the production-style preview app.
  local:reset       Reset the local Supabase DB from migrations and seed.sql.
  local:status      Show local Supabase and app container status.
  local:stop        Stop app containers and local Supabase, keeping DB data.
  local:destroy     Stop everything and remove local app/Supabase volumes.
  local:logs        Follow app container logs.
USAGE
}

die() {
  echo "local-stack: $*" >&2
  exit 1
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

ensure_tools() {
  need_cmd docker
  docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required."
  [[ -x "$SUPABASE_BIN" ]] || die "Supabase CLI is not installed. Run npm ci first."
}

supabase_cli() {
  "$SUPABASE_BIN" "$@"
}

redact_secrets() {
  sed -E \
    -e 's/sb_secret_[A-Za-z0-9_-]+/<redacted-secret>/g' \
    -e 's/(SERVICE_ROLE_KEY=).*/\1<redacted>/g' \
    -e 's/(SECRET_KEY=).*/\1<redacted>/g' \
    -e 's/(JWT_SECRET=).*/\1<redacted>/g' \
    -e 's/(Secret Key[[:space:]]*│ )[A-Za-z0-9]+/\1<redacted>/g' \
    -e 's/(Access Key[[:space:]]*│ )[A-Za-z0-9]+/\1<redacted>/g'
}

supabase_cli_logged() {
  set +e
  "$SUPABASE_BIN" "$@" 2>&1 | redact_secrets
  local exit_code="${PIPESTATUS[0]}"
  set -e
  return "$exit_code"
}

docker_compose() {
  docker compose "$@"
}

is_local_supabase_url() {
  case "$1" in
    http://127.0.0.1:54321*|http://localhost:54321*) return 0 ;;
    *) return 1 ;;
  esac
}

env_file_value() {
  local file="$1"
  local name="$2"
  [[ -f "$file" ]] || return 0

  local value
  value="$(grep -E "^${name}=" "$file" | tail -n 1 | cut -d= -f2- || true)"
  value="${value%$'\r'}"
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  printf '%s' "$value"
}

extract_status_env() {
  local name="$1"
  local status_env="$2"
  local value
  value="$(printf '%s\n' "$status_env" | awk -F= -v key="$name" '$1 == key { print substr($0, length(key) + 2); exit }')"
  value="${value%$'\r'}"
  value="${value%\"}"
  value="${value#\"}"
  value="${value%\'}"
  value="${value#\'}"
  printf '%s' "$value"
}

start_supabase() {
  echo "Starting local Supabase..."
  supabase_cli_logged start
}

reset_local_db() {
  echo "Resetting local Supabase database from migrations..."
  supabase_cli db reset --local
}

seed_local_test_user() {
  local status_env
  local api_url
  local service_role_key

  status_env="$(supabase_cli status -o env)"
  api_url="$(extract_status_env API_URL "$status_env")"
  service_role_key="$(extract_status_env SERVICE_ROLE_KEY "$status_env")"

  [[ -n "$api_url" ]] || die "Could not read local API_URL from Supabase status."
  [[ -n "$service_role_key" ]] || die "Could not read local SERVICE_ROLE_KEY from Supabase status."
  is_local_supabase_url "$api_url" || die "Refusing to seed a non-local Supabase URL: $api_url"

  echo "Seeding local E2E user..."
  SUPABASE_URL="$api_url" \
    SUPABASE_SERVICE_ROLE_KEY="$service_role_key" \
    node scripts/seed-local-test-user.mjs
}

write_local_env() {
  local status_env
  local api_url
  local anon_key
  local current_url
  local tmp_file

  status_env="$(supabase_cli status -o env)"
  api_url="$(extract_status_env API_URL "$status_env")"
  anon_key="$(extract_status_env ANON_KEY "$status_env")"

  [[ -n "$api_url" ]] || die "Could not read local API_URL from Supabase status."
  [[ -n "$anon_key" ]] || die "Could not read local ANON_KEY from Supabase status."
  is_local_supabase_url "$api_url" || die "Refusing to write non-local Supabase URL: $api_url"

  tmp_file="$(mktemp)"
  if [[ -f "$LOCAL_ENV_FILE" ]]; then
    current_url="$(env_file_value "$LOCAL_ENV_FILE" VITE_SUPABASE_URL)"
    if [[ -n "$current_url" ]] && ! is_local_supabase_url "$current_url"; then
      local backup_file
      backup_file="$LOCAL_ENV_FILE.backup.$(date +%Y%m%d%H%M%S)"
      cp "$LOCAL_ENV_FILE" "$backup_file"
      echo "Backed up existing non-local .env.local to ${backup_file#$ROOT_DIR/}"
    fi

    awk '!/^(VITE_SUPABASE_URL|VITE_SUPABASE_ANON_KEY)=/' "$LOCAL_ENV_FILE" > "$tmp_file"
  else
    printf '# Local environment generated by scripts/local-stack.sh\n' > "$tmp_file"
  fi

  {
    cat "$tmp_file"
    printf '\n# Local Supabase stack. Keep these local for local runs.\n'
    printf 'VITE_SUPABASE_URL=%s\n' "$api_url"
    printf 'VITE_SUPABASE_ANON_KEY=%s\n' "$anon_key"
  } > "$LOCAL_ENV_FILE"

  rm -f "$tmp_file"
  echo "Wrote .env.local for local Supabase at $api_url"
}

assert_local_env() {
  local configured_url
  configured_url="$(env_file_value "$LOCAL_ENV_FILE" VITE_SUPABASE_URL)"
  [[ -n "$configured_url" ]] || die ".env.local is missing VITE_SUPABASE_URL."
  is_local_supabase_url "$configured_url" || die ".env.local points to a non-local Supabase URL: $configured_url"
}

print_urls() {
  cat <<URLS

Local stack is up.
  App:             $LOCAL_APP_URL
  Supabase API:    http://127.0.0.1:54321
  Supabase Studio: http://127.0.0.1:54323
  Inbucket email:  http://127.0.0.1:54324
  Postgres:        postgresql://postgres:postgres@127.0.0.1:54322/postgres
URLS
}

up_dev() {
  start_supabase
  write_local_env
  seed_local_test_user
  assert_local_env
  echo "Starting Docker dev app..."
  docker_compose up -d --build app
  print_urls
}

up_fresh() {
  start_supabase
  reset_local_db
  write_local_env
  seed_local_test_user
  assert_local_env
  echo "Starting Docker dev app..."
  docker_compose up -d --build app
  print_urls
}

up_preview() {
  start_supabase
  write_local_env
  seed_local_test_user
  assert_local_env
  echo "Starting Docker preview app..."
  docker_compose --profile preview up -d --build app-preview
  print_urls
}

show_status() {
  ensure_tools
  local status_output
  local api_url
  local db_url
  local studio_url
  local inbucket_url

  echo "Supabase:"
  if status_output="$(supabase_cli status -o env 2>/dev/null)"; then
    api_url="$(extract_status_env API_URL "$status_output")"
    db_url="$(extract_status_env DB_URL "$status_output")"
    studio_url="$(extract_status_env STUDIO_URL "$status_output")"
    inbucket_url="$(extract_status_env INBUCKET_URL "$status_output")"

    echo "Supabase local stack is running."
    [[ -n "$api_url" ]] && echo "  API:       $api_url"
    [[ -n "$api_url" ]] && echo "  Functions: $api_url/functions/v1"
    [[ -n "$studio_url" ]] && echo "  Studio:    $studio_url"
    [[ -n "$inbucket_url" ]] && echo "  Inbucket:  $inbucket_url"
    [[ -n "$db_url" ]] && echo "  Postgres:  $db_url"
  else
    echo "Supabase local stack is not running."
  fi
  echo
  echo "Docker app:"
  docker_compose ps -a
}

stop_stack() {
  ensure_tools
  docker_compose down
  supabase_cli stop
}

destroy_stack() {
  ensure_tools
  docker_compose down -v
  supabase_cli stop --no-backup
}

follow_logs() {
  ensure_tools
  docker_compose logs -f app
}

main() {
  local command="${1:-}"

  case "$command" in
    up)
      ensure_tools
      up_dev
      ;;
    fresh)
      ensure_tools
      up_fresh
      ;;
    preview)
      ensure_tools
      up_preview
      ;;
    reset)
      ensure_tools
      start_supabase
      reset_local_db
      write_local_env
      seed_local_test_user
      assert_local_env
      ;;
    status)
      show_status
      ;;
    stop)
      stop_stack
      ;;
    destroy)
      destroy_stack
      ;;
    logs)
      follow_logs
      ;;
    -h|--help|help|"")
      usage
      ;;
    *)
      usage
      die "Unknown command: $command"
      ;;
  esac
}

main "$@"
